# Generated by Django 3.2.18 on 2023-03-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrocard',
            old_name='user',
            new_name='userprofile',
        ),
    ]
