# Generated by Django 3.2.18 on 2023-03-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_googlerequest_socialprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrocard',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
    ]
