# Generated by Django 3.2.18 on 2023-03-05 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_metrocard_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14)]),
        ),
    ]
