# Generated by Django 3.2.18 on 2023-03-07 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrocard',
            name='balance',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
