# Generated by Django 3.2.18 on 2023-03-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TravelCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('station_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_1', to='journeys.station')),
                ('station_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_2', to='journeys.station')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.station')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination', to='journeys.station')),
                ('metro_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.metrocard')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='origin', to='journeys.station')),
            ],
        ),
    ]
