# Generated by Django 3.2.18 on 2023-03-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeypayment',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.journey'),
        ),
    ]
