# Generated by Django 3.2.18 on 2023-03-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_metrocard_userprofile'),
        ('journeys', '0002_alter_journeypayment_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='journeys.station'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='metro_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.metrocard'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='journeys.station'),
        ),
    ]
