# Generated by Django 3.2.18 on 2023-03-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_auto_20230305_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='journey_type',
            field=models.CharField(choices=[('single', 'single'), ('open_return', 'open_return')], default='single', max_length=16),
        ),
    ]
